import { PrismaClient as Prisma } from '@prisma/client';

const prisma = new Prisma();

const HOTELS = [
  {
    id: 'hotel-001',
    name: 'Grand Hotel Kinshasa',
    address: 'Avenue de la Liberté 123',
    city: 'Kinshasa',
    country: 'DRC',
    latitude: -4.4419,
    longitude: 15.2663,
    phone: '+243 81 000 1111',
    email: 'reservations@grandhotelkin.cd',
    website: 'https://grandhotelkin.cd',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099942?w=800&q=80',
    starRating: 4,
    pricePerNight: 150,
    amenities: 'Wi-Fi, Restaurant, Pool, Gym, Spa, Parking, 24h Reception, Laundry',
    description: 'A premier 4-star hotel in the heart of Kinshasa, offering elegant rooms, a rooftop restaurant with panoramic views, and exceptional service. Perfect for business travelers and tourists alike.',
    status: 'active',
  },
  {
    id: 'hotel-002',
    name: 'Hotel Lubumbashi City',
    address: 'Boulevard Communaautaire 456',
    city: 'Lubumbashi',
    country: 'DRC',
    latitude: -11.6653,
    longitude: 27.4744,
    phone: '+243 82 000 2222',
    email: 'info@hotel-lub.cd',
    website: 'https://hotellub.cd',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
    starRating: 3,
    pricePerNight: 85,
    amenities: 'Wi-Fi, Restaurant, Parking, 24h Reception, Laundry, Safe',
    description: 'Comfortable 3-star hotel in the mining capital of DRC. Clean, reliable, and affordable with a delightful restaurant serving local cuisine.',
    status: 'active',
  },
  {
    id: 'hotel-003',
    name: 'Mountain View Hotel Goma',
    address: 'Rue de la Paix 78',
    city: 'Goma',
    country: 'DRC',
    latitude: -1.6695,
    longitude: 29.1831,
    phone: '+243 83 000 3333',
    email: 'goma@mvhotel.cd',
    website: 'https://mvhotelgoma.cd',
    image: 'https://images.unsplash.com/photo-1571896349842-2d2996160d3c?w=800&q=80',
    starRating: 3.5,
    pricePerNight: 95,
    amenities: 'Wi-Fi, Restaurant, Lake View, Parking, 24h Security, Tour Desk',
    description: 'Nestled near Lake Kivu with stunning views of the Virunga volcanoes. A peaceful retreat for travelers exploring the eastern DRC.',
    status: 'active',
  },
  {
    id: 'hotel-004',
    name: 'Kisangani River Hotel',
    address: 'Quai du Fleuve 12',
    city: 'Kisangani',
    country: 'DRC',
    latitude: 0.4833,
    longitude: 25.0283,
    phone: '+243 84 000 4444',
    email: 'accueil@khhotel.cd',
    website: 'https://kisanganihotel.cd',
    image: 'https://images.unsplash.com/photo-1584132961994-7c424ba49d8d?w=800&q=80',
    starRating: 2.5,
    pricePerNight: 55,
    amenities: 'Wi-Fi, Restaurant, Bar, Lake View, Parking',
    description: 'A charming hotel on the banks of the Congo River. Affordable and comfortable, ideal for exploring Kisangani and the surrounding rainforest.',
    status: 'active',
  },
  {
    id: 'hotel-005',
    name: 'Saphir Hotel Kinshasa',
    address: 'Avenue des Aviateurs 99',
    city: 'Kinshasa',
    country: 'DRC',
    latitude: -4.3785,
    longitude: 15.3064,
    phone: '+243 81 000 5555',
    email: 'contact@saphirhotelkin.cd',
    website: 'https://saphirkin.cd',
    image: 'https://images.unsplash.com/photo-1631049301915-3157344c44f1?w=800&q=80',
    starRating: 5,
    pricePerNight: 280,
    amenities: 'Wi-Fi, Multiple Restaurants, Pool, Full Spa, Gym, Valet Parking, Concierge, Airport Shuttle, Meeting Rooms, Wedding Hall',
    description: 'A 5-star luxury hotel in Kinshasa, featuring stunning interiors, world-class dining, and impeccable service. The ultimate taste of Congolese hospitality.',
    status: 'active',
  },
  {
    id: 'hotel-006',
    name: 'Hotel Basengere Bukavu',
    address: 'Avenue de la Libération 1',
    city: 'Bukavu',
    country: 'DRC',
    latitude: -2.5094,
    longitude: 28.8450,
    phone: '+243 85 000 6666',
    email: 'reseaux@basengere.cd',
    website: 'https://basengere Bukavu.cd',
    image: 'https://images.unsplash.com/photo-1590490359683-658d3d23f98e?w=800&q=80',
    starRating: 2,
    pricePerNight: 40,
    amenities: 'Wi-Fi, Restaurant, Lake View, Parking',
    description: 'A basic but clean and welcoming hotel on the shores of Lake Kivu. Great budget option for travelers exploring the South Kivu region.',
    status: 'active',
  },
  {
    id: 'hotel-007',
    name: 'Concord Hotel Matadi',
    address: 'Route Nationale 15',
    city: 'Matadi',
    country: 'DRC',
    latitude: -5.8238,
    longitude: 13.4500,
    phone: '+243 86 000 7777',
    email: 'info@concordmatadi.cd',
    website: 'https://concordmatadi.cd',
    image: 'https://images.unsplash.com/photo-1590501879037-b9a6b3b8c9b3?w=800&q=80',
    starRating: 2,
    pricePerNight: 35,
    amenities: 'Wi-Fi, Restaurant, Parking',
    description: 'A modest hotel at the gateway to the DRC. Perfect stopover for travelers entering or leaving the country via the Congo River port.',
    status: 'active',
  },
  {
    id: 'hotel-008',
    name: 'Hotel Kinkambo Bandundu',
    address: 'Centre Ville 88',
    city: 'Bandundu',
    country: 'DRC',
    latitude: -3.0333,
    longitude: 19.0200,
    phone: '+243 87 000 8888',
    email: 'contact@kinkambo.cd',
    website: 'https://kinkambo hotel.cd',
    image: 'https://images.unsplash.com/photo-1445019980597-958cb4b80d31?w=800&q=80',
    starRating: 2.5,
    pricePerNight: 48,
    amenities: 'Wi-Fi, Restaurant, Safe, Laundry',
    description: 'A comfortable hotel in the heart of Bandundu. Good value for money with friendly staff and clean rooms.',
    status: 'active',
  },
  {
    id: 'hotel-009',
    name: 'Le Royal Hotel Kisangani',
    address: 'Quai du Fleuve 90',
    city: 'Kisangani',
    country: 'DRC',
    latitude: 0.4833,
    longitude: 25.0283,
    phone: '+243 88 000 9999',
    email: 'royal@kisanganiveryhotel.cd',
    website: 'https://royalkisangani.cd',
    image: 'https://images.unsplash.com/photo-1564501990906-1c1f2e436ce5?w=800&q=80',
    starRating: 3,
    pricePerNight: 75,
    amenities: 'Wi-Fi, Restaurant, Pool, Bar, Parking, Laundry',
    description: 'The only hotel in Kisangani with a swimming pool. Enjoy the river breeze and tropical gardens in a relaxed colonial setting.',
    status: 'active',
  },
  {
    id: 'hotel-010',
    name: 'Mwenze Hotel Kananga',
    address: 'Zone Industrielle 5',
    city: 'Kananga',
    country: 'DRC',
    latitude: -6.0900,
    longitude: 23.4800,
    phone: '+243 89 000 0001',
    email: 'accueil@mwenzekananga.cd',
    website: 'https://mwenzekananga.cd',
    image: 'https://images.unsplash.com/photo-1502728879834-0608288da472?w=800&q=80',
    starRating: 2,
    pricePerNight: 42,
    amenities: 'Wi-Fi, Restaurant, Laundry, Parking',
    description: 'A simple but comfortable hotel in central Kananga. Reliable Wi-Fi and friendly staff make this a great base for exploring Kasai-Central.',
    status: 'active',
  },
];

const REVIEWS = [
  {
    hotelId: 'hotel-001',
    guestName: 'Jean-Pierre M.',
    guestEmail: 'jp@example.com',
    rating: 5,
    comment: 'Absolutely magnificent hotel. The rooftop restaurant offers the best view in Kinshasa. Staff were incredibly attentive and professional.',
    cleanliness: 5,
    location: 5,
    staff: 5,
    value: 4,
  },
  {
    hotelId: 'hotel-001',
    guestName: 'Sarah K.',
    guestEmail: 'sarah@example.com',
    rating: 4,
    comment: 'Great hotel, really well located. The rooms are spacious and the Wi-Fi is fast. Only minor complaint: breakfast could be more varied.',
    cleanliness: 4,
    location: 5,
    staff: 4,
    value: 4,
  },
  {
    hotelId: 'hotel-005',
    guestName: 'Marcel T.',
    guestEmail: 'marcel@example.com',
    rating: 5,
    comment: 'World-class hotel! Everything from check-in to check-out was flawless. The spa is incredible and the concierge arranged everything perfectly.',
    cleanliness: 5,
    location: 5,
    staff: 5,
    value: 5,
  },
  {
    hotelId: 'hotel-003',
    guestName: 'Anna D.',
    guestEmail: 'anna@example.com',
    rating: 4,
    comment: 'Wonderful stay with amazing views of Lake Kivu. The tour desk helped us organize a trip to see the volcanoes. Would stay again.',
    cleanliness: 4,
    location: 5,
    staff: 4,
    value: 5,
  },
  {
    hotelId: 'hotel-002',
    guestName: 'David R.',
    guestEmail: 'david@example.com',
    rating: 3,
    comment: 'Perfectly adequate for a stopover in Lubumbashi. Clean rooms, decent food. Not luxurious but good value for money in this region.',
    cleanliness: 3,
    location: 4,
    staff: 3,
    value: 4,
  },
];

async function main() {
  console.log('Seeding hotels...');

  for (const hotel of HOTELS) {
    await prisma.hotel.upsert({
      where: { id: hotel.id },
      update: hotel,
      create: hotel,
    });
    console.log(`✓ ${hotel.name} (${hotel.city})`);
  }

  for (const review of REVIEWS) {
    await prisma.hotelReview.upsert({
      where: { id: `${review.hotelId}-${review.guestEmail}` },
      update: review,
      create: { ...review, id: `${review.hotelId}-${review.guestEmail}` },
    });
    console.log(`✓ Review for ${review.hotelId} by ${review.guestName}`);
  }

  console.log('Seed complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
