export const ID_TYPES = [
  { value: 'passport',         label: 'Passport',             desc: 'International travel document',        icon: 'M12 2C8.1 2 5 5.1 5 9v3c0 4 3 6 3 6s3-2 3-6V9c0-3.9-3.1-7-7-7zM12 11c-1.6 0-3 .8-3 2s1.4 2 3 2 3-.8 3-2-1.4-2-3-2z', government: true },
  { value: 'national_id',      label: 'National ID (CNI)',    desc: 'Carte Nationale d\'Identité (DRC)',     icon: 'M17 2H7a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8l-7-4zM15 11H7v-2h8v2zm0-4H7V5h8v2zm0-4H7V3h8v2z', government: true },
  { value: 'drivers_license',  label: 'Driver\'s license',    desc: 'Permis de conduire',                    icon: 'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z', government: true },
  { value: 'voter_card',       label: 'Voter card',           desc: 'Carte électorale (DRC)',                icon: 'M9 11l3 3L22 4l-3-3-10 10z M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z', government: true },
  { value: 'student_id',       label: 'Student ID',           desc: 'University / school card',              icon: 'M22 10v6M2 10l10-5 10 5M4 18v-6M20 18v-6M4 18h16', government: false },
  { value: 'residence_permit', label: 'Residence permit',     desc: 'Permis de séjour / résidence',         icon: 'M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z M12 6v6m-3 3h6', government: true },
  { value: 'other',            label: 'Other document',       desc: 'Any other accepted ID',                 icon: 'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z M14 2v6h6', government: false },
] as const;

export type IdTypeValue = typeof ID_TYPES[number]['value'];

export const DRC_COUNTRIES = [
  { value: 'CD', label: 'DRC' },
  { value: 'CG', label: 'Congo-Brazzaville' },
  { value: 'AO', label: 'Angola' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabwe' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'UG', label: 'Uganda' },
  { value: 'RW', label: 'Rwanda' },
  { value: 'BI', label: 'Burundi' },
  { value: 'SO', label: 'Somalia' },
  { value: 'KE', label: 'Kenya' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'NA', label: 'Namibia' },
  { value: 'BW', label: 'Botswana' },
  { value: 'SD', label: 'Sudan' },
  { value: 'SS', label: 'South Sudan' },
  { value: 'CF', label: 'CAR' },
  { value: 'TD', label: 'Chad' },
  { value: 'CN', label: 'China' },
  { value: 'US', label: 'United States' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'FR', label: 'France' },
  { value: 'BE', label: 'Belgium' },
  { value: 'DE', label: 'Germany' },
  { value: 'IT', label: 'Italy' },
  { value: 'ES', label: 'Spain' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'AE', label: 'UAE' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'CI', label: 'Côte d\'Ivoire' },
  { value: 'SN', label: 'Senegal' },
  { value: 'GH', label: 'Ghana' },
  { value: 'CM', label: 'Cameroon' },
  { value: 'GA', label: 'Gabon' },
  { value: 'GQ', label: 'Equatorial Guinea' },
  { value: 'other', label: 'Other' },
] as const;
